### ISSUE TITLE
File storage doesn't work

### ISSUE THREAD

**Issue by Ribesg** [neandrake/haste-server#42]
I got multiple problems trying to use file storage. Switched to redis and it works, but you may want to either fix it or remove the feature.
Nice work on this!

**Comment by neandrake** [comment]
Some of the additional features I've added need to track extra metadata aside from just the file itself. The file storage likely no longer works due to this, and you're right it should probably just be removed.

**Comment by neandrake** [comment]
I removed all file stores except redis since they were not kept current/compatible. If future contributors wish to supply other file stores, pull requests will be accepted.
